#!/bin/bash
# 录音功能测试和验证脚本

echo "🎤 录音功能启用完成！"
echo "=========================================="
echo ""
echo "✅ 已完成的配置："
echo "1. 重新启用了浏览器录音功能"
echo "2. 添加了完整的MediaRecorder支持"
echo "3. 配置了音频数据处理"
echo "4. 添加了详细的错误处理"
echo "5. 支持多种音频格式"
echo ""
echo "📱 测试录音功能"
echo "=========================================="
echo ""
echo "步骤1：打开录音页面"
echo "访问：https://corp0.hz-college.com/"
echo "找到：克隆新音色功能"
echo ""
echo "步骤2：选择录音模式"
echo "- 点击'录音'按钮"
echo "- 允许浏览器访问麦克风权限"
echo "- 点击'允许'"
echo ""
echo "步骤3：开始录音"
echo "- 点击'开始录音'按钮"
echo "- 对着麦克风清晰说话3-5秒"
echo "- 系统会自动停止录音"
echo ""
echo "步骤4：上传并克隆"
echo "- 录音完成后，点击'上传'按钮"
echo "- 等待音色克隆完成"
echo "- 输入音色名称"
echo "- 点击'保存音色'"
echo ""
echo "⚠️  常见问题排查"
echo "=========================================="
echo ""
echo "问题1：无法访问麦克风"
echo "解决："
echo "- 检查浏览器是否允许麦克风权限"
echo "- 检查系统麦克风是否被其他应用占用"
echo "- 尝试刷新页面重新请求权限"
echo ""
echo "问题2：录音质量不好"
echo "解决："
echo "- 在安静环境中录音"
echo "- 确保说话清晰，音量适中"
echo "- 麦离麦克风适当距离"
echo ""
echo "问题3：录音时间限制"
echo "说明："
echo "- 默认最长录音时间：3秒"
echo "- 可以修改代码调整 maxDuration 参数"
echo "- 建议录制3-5秒的音频样本"
echo ""
echo "问题4：HTTPS要求"
echo "说明："
echo "- 现代浏览器要求HTTPS才能使用录音功能"
echo "- 已配置：https://corp0.hz-college.com"
echo "- SSL证书：有效"
echo ""
echo "🎯 最佳实践建议"
echo "=========================================="
echo ""
echo "1. 录音环境："
echo "   - 选择安静的环境"
echo "   - 避免背景噪音"
echo "   - 保持适当距离（10-30cm）"
echo ""
echo "2. 录音内容："
echo "   - 说话清晰，音量适中"
echo "   - 使用标准普通话"
echo "   - 录制3-5秒的样本"
echo "   - 内容示例：'欢迎使用音色复刻服务'"
echo ""
echo "3. 备选方案："
echo "   - 如果录音功能不兼容"
echo "   - 可以使用'上传文件'模式"
echo "   - 支持MP3和WAV格式"
echo "   - 质量更稳定可靠"
echo ""
echo "🔧 技术细节"
echo "=========================================="
echo ""
echo "支持的音频格式："
echo "- audio/webm (首选)"
echo "- audio/mp4"
echo "- audio/ogg"
echo "- audio/wav"
echo ""
echo "音频配置："
echo "- 采样率：44100 Hz"
echo "- 声道：单声道"
echo "- 回声消除：启用"
echo "- 噪声抑制：启用"
echo ""
echo "📊 系统状态"
echo "=========================================="
echo ""
echo "检查服务状态..."
ssh hongzhi "echo '应用状态:' && pm2 list | grep openmaic-web && echo '' && echo 'HTTPS状态:' && curl -sI https://corp0.hz-college.com | head -1"
echo ""
echo "=========================================="
echo "🚀 现在可以测试录音功能了！"
echo ""
echo "访问：https://corp0.hz-college.com/"
echo "找到克隆新音色功能，点击'录音'按钮开始测试"
