#!/bin/bash
# 微信小程序快速配置指南

echo "🎉 OpenMAIC 微信小程序快速配置指南"
echo "=========================================="
echo ""
echo "✅ HTTPS配置已完成！"
echo "🌐 域名：https://corp0.hz-college.com"
echo "🔒 SSL证书：已安装并配置自动续期"
echo ""
echo "📱 立即配置微信小程序（5分钟）"
echo "=========================================="
echo ""
echo "第一步：登录微信小程序后台"
echo "-----------------------------------"
echo "1. 访问：https://mp.weixin.qq.com/"
echo "2. 使用管理员账号扫码登录"
echo ""
echo "第二步：添加服务器域名"
echo "-----------------------------------"
echo "路径：开发 → 开发管理 → 开发设置 → 服务器域名"
echo ""
echo "需要添加以下域名："
echo ""
echo "📌 request合法域名："
echo "https://corp0.hz-college.com"
echo ""
echo "📌 uploadFile合法域名："
echo "https://corp0.hz-college.com"
echo ""
echo "📌 downloadFile合法域名："
echo "https://corp0.hz-college.com"
echo ""
echo "第三步：保存配置"
echo "-----------------------------------"
echo "1. 点击“保存”按钮"
echo "2. 配置立即生效"
echo "3. 每月只能修改5次，请谨慎操作"
echo ""
echo "🧪 测试验证"
echo "=========================================="
echo ""
echo "1. API测试："
echo "curl https://corp0.hz-college.com/api/health"
echo ""
echo "2. 在微信开发者工具中测试："
echo "- 打开项目"
echo "- 点击“预览”"
echo "- 用微信扫码真机测试"
echo ""
echo "3. 如果显示域名不合法："
echo "- 检查是否正确添加了服务器域名"
echo "- 确认使用HTTPS协议"
echo "- 等待5分钟后再试"
echo ""
echo "⚠️  注意事项"
echo "=========================================="
echo ""
echo "1. 微信小程序强制要求HTTPS"
echo "2. 域名不能包含端口号"
echo "3. 配置后立即生效，无需重启应用"
echo "4. 体验版和生产环境使用相同域名"
echo "5. 审核周期1-7天，请提前准备材料"
echo ""
echo "📖 详细文档"
echo "=========================================="
echo ""
echo "完整部署指南："
echo "docs/HTTPS_CONFIG_COMPLETE.md"
echo ""
echo "微信小程序部署："
echo "docs/WECHAT_MINIPROGRAM_DEPLOYMENT.md"
echo ""
echo "🎯 配置完成后"
echo "=========================================="
echo ""
echo "1. 进行真机功能测试"
echo "2. 上传体验版给用户测试"
echo "3. 准备审核材料并提交"
echo "4. 等待审核通过后发布"
echo ""
echo "🚀 开始配置吧！"
echo "打开浏览器访问：https://mp.weixin.qq.com/"
